### ISSUE TITLE
NGINX: Redirect fails without trailing slash

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/dockerfiles#2]
Links without a trailing slash don't redirect correctly:

1. [broken] https://openmobility.eclipse.org/technologies/eclipse-sumo
2. [works] https://openmobility.eclipse.org/technologies/eclipse-sumo/

Same problem is occuring with https://openadx.eclipse.org/resources

**Comment by mbarbero** [comment]
Fixed in commit aa9dd6c
